// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDapkO6LqYawyD3PtyXJp4qcrYzgOZsIEo',
    appId: '1:977743006223:web:6a65c8d5affb293c00f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    authDomain: 'newotp-60ee9.firebaseapp.com',
    storageBucket: 'newotp-60ee9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6suH9aTSJ8U7bDFiv9cmkh-IzSGT_iE',
    appId: '1:977743006223:android:1ca29e8bf89e8b4000f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    storageBucket: 'newotp-60ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOd-KqahjNKvlUNvneWyoc1ok5umJ5fEI',
    appId: '1:977743006223:ios:37d5db1a187e84a600f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    storageBucket: 'newotp-60ee9.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOd-KqahjNKvlUNvneWyoc1ok5umJ5fEI',
    appId: '1:977743006223:ios:b864843e78101c5d00f17a',
    messagingSenderId: '977743006223',
    projectId: 'newotp-60ee9',
    storageBucket: 'newotp-60ee9.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
