// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQC8G6Va6dxmKV9jTAnmx8gNSxMENIpE',
    appId: '1:487559396972:web:94fb6901681bc095a5a249',
    messagingSenderId: '487559396972',
    projectId: 'otpdemo-338f4',
    authDomain: 'otpdemo-338f4.firebaseapp.com',
    storageBucket: 'otpdemo-338f4.appspot.com',
    measurementId: 'G-9NTS8QQ12S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYR_Uu_Ow_8PotjMOBv5u1112s1sO7tqc',
    appId: '1:487559396972:android:841476288ec5fbf1a5a249',
    messagingSenderId: '487559396972',
    projectId: 'otpdemo-338f4',
    storageBucket: 'otpdemo-338f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOkg46gBdxjRz9y6uz9uSkvNETpLKnnYc',
    appId: '1:487559396972:ios:f30737ce6a8226a5a5a249',
    messagingSenderId: '487559396972',
    projectId: 'otpdemo-338f4',
    storageBucket: 'otpdemo-338f4.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOkg46gBdxjRz9y6uz9uSkvNETpLKnnYc',
    appId: '1:487559396972:ios:8ed3ed37767ba3ada5a249',
    messagingSenderId: '487559396972',
    projectId: 'otpdemo-338f4',
    storageBucket: 'otpdemo-338f4.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
